export const primaryNav = [
  ["Home", "/"],
  ["About Us", "/about"],
  ["Courses", "/courses"],
  ["Affiliation", "/affiliation"],
  ["Fee Structure", "/fee-structure"],
  ["Schools", "/schools"],
  ["AI Centers", "/ai-centers"],
  ["Study Material", "/study-material"],
  ["About State", "/about-state"],
  ["Board Profile", "/board-profile"],
  ["Calendar", "/calendar"],
  ["FAQ", "/faq"],
  ["Contact Us", "/contact"],
] as const;
